### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by Ectario** [Ectario/SmartHelper#3]
## TODOS
- [ ] Create unit tests to verify slot number

To check the slots number, let's use the compiler json output [compiler](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description) 
- [ ] Create unit tests to verify name generation for mappings

To check the name generation see Parse Name at #2 
- [ ] Verify the Path parsing (ex: "Keccak(0)" as a Path in the path parsing function must return the good value)
- [ ] Create unit tests to verify the path generation

To check the path generation see let's calculate using the path and verify that it's equal to the slot number
- [ ] Create unit tests to verify json structure
  - [ ] Each property exist
  - [ ] Each property is rightly set

To check the properties, see Context at #2, [Struct](https://github.com/Ectario/SmartHelper/examples/outputs/struct.md) and [Mapping](https://github.com/Ectario/SmartHelper/examples/outputs/mapping.md )
