### ISSUE TITLE
Create sample smart contracts for testing

### ISSUE THREAD

**Issue by RaxoCoding** [Ectario/SmartHelper#4]
## TODO
- [ ] Simple contract
- [ ] Contract with Maps
- [ ] Contract with Maps of Maps
- [ ] Contract with Structs
- [ ] Contract with Structs in Maps
- [ ] Contract with Maps in Structs
