### ISSUE TITLE
Write initial documentation

### ISSUE THREAD

**Issue by RaxoCoding** [Ectario/SmartHelper#6]
## TODO
- [ ] Doc on project goal and its usecases
- [ ] Doc on using core
- [ ] Doc of input provided to core
- [ ] Doc specifying the output of core
  - [ ] Explain each property in the storage.json output
- [ ] Doc on creating Issues & Contributing
